(function () {
  const base = window.DRATOS_CONTENT.pt;
  const merge = (target, source) => {
    Object.keys(source).forEach((key) => {
      if (source[key] && typeof source[key] === "object" && !Array.isArray(source[key])) target[key] = merge({ ...(target[key] || {}) }, source[key]);
      else target[key] = source[key];
    });
    return target;
  };

  window.DRATOS_CONTENT.es = merge(structuredClone(base), {
    meta: { lang: "es", label: "ES", title: "DRATOS | Gobernanza Contractual Inteligente", description: "Conecte datos, personas, documentos, aprobaciones, firmas, obligaciones, desempeño y evidencias en una jornada contractual gobernada.", organization: { name: "DRATOS — Contratos Inteligentes", description: "Plataforma de gobernanza del ciclo de vida contractual." } },
    accessibility: { skip: "Saltar al contenido", openMenu: "Abrir menú", closeMenu: "Cerrar menú", changeLanguage: "Cambiar idioma", toggleTheme: "Cambiar tema", closeModal: "Cerrar ventana", previous: "Anterior", next: "Siguiente", primaryNavigation: "Navegación principal" },
    visual: { brand: "DRATOS", productLabel: "DRATOS / EJECUTIVO", live: "EN VIVO", presenterInitial: "H", fragments: ["PDF", "DOCX", "XLSX", "CORREO", "CHAT", "V1.2", "APROBACIÓN", "PLAZO"], accessCore: "RBAC", totvsSource: "TOTVS RM" },
    nav: [["Visión general", "visao-geral"], ["Jornada", "jornada"], ["Plataforma", "plataforma"], ["Desempeño", "performance"], ["Integraciones", "integracoes"], ["Seguridad", "seguranca"], ["Videos", "videos"], ["Planes", "planos"]],
    actions: { demo: "Agendar demostración", journey: "Explorar la jornada", watch: "Ver video", diagnose: "Solicitar diagnóstico", program: "Participar del programa", details: "Ver detalles", technical: "Explorar arquitectura", send: "Generar solicitud", back: "Volver", close: "Cerrar", play: "Reproducir" },
    header: { descriptor: "Gobernanza Contractual Inteligente" },
    hero: {
      eyebrow: "Contratos Inteligentes · Gobernanza Contractual", title: "De datos dispersos a decisiones gobernadas.",
      text: "DRATOS conecta datos, personas, documentos, cláusulas, aprobaciones, firmas, obligaciones, desempeño y evidencias en una única jornada contractual.",
      note: "DRATOS no sustituye al ERP. Conecta y gobierna la jornada a partir de los datos que su organización ya posee.", stageLabel: "Jornada contractual en tiempo real",
      stages: ["Datos", "Solicitud", "Autoría", "Aprobación", "Firma", "Gestión", "Desempeño"],
      metrics: [{ label: "SLA demostrativo", value: "94%", trend: "+6,2%" }, { label: "Entregas realizadas", value: "98%", trend: "+4,8%" }, { label: "Evaluación general", value: "4,8", trend: "★★★★★" }],
      status: ["Flujo trazable", "Evidencias conectadas", "Acceso por contexto"], trust: ["Empresas privadas", "Gobierno y estatales", "Organizaciones reguladas", "Operaciones multiempresa"]
    },
    problem: {
      eyebrow: "El caos invisible", title: "Los datos están en los sistemas. El contrato sigue disperso.", text: "Correos, hojas de cálculo, versiones paralelas y aprobaciones fuera del flujo reducen la visibilidad y dificultan la auditoría.", evidenceLabel: "Fragmentos por contrato", evidenceValue: "12+", evidenceNote: "Escenario ilustrativo: archivos, mensajes, hojas, aprobaciones y evidencias desconectadas.",
      items: [{ number: "01", title: "Versiones paralelas", text: "La minuta correcta se pierde entre adjuntos y copias locales." }, { number: "02", title: "Decisiones sin contexto", text: "Aprobaciones y salvedades quedan separadas del documento." }, { number: "03", title: "Plazos olvidados", text: "Las obligaciones comienzan después de la firma, pero el seguimiento no." }, { number: "04", title: "Indicadores tardíos", text: "El desempeño llega cuando ya es difícil actuar." }]
    },
    promise: { eyebrow: "La respuesta DRATOS", title: "Un contrato vivo, de la solicitud al desempeño.", text: "La plataforma convierte archivos aislados en una operación conectada, parametrizable y verificable.", before: { label: "Antes", title: "Archivo estático", items: ["Datos duplicados", "Historial fragmentado", "Gestión reactiva"] }, after: { label: "Con DRATOS", title: "Jornada gobernada", items: ["Contexto único", "Reglas configurables", "Evidencias e indicadores"] } },
    journey: {
      eyebrow: "Demostración guiada", title: "Una historia completa en 16 escenas.", text: "Helena, presentadora oficial de DRATOS, conduce la narrativa con identidad, ambiente y lenguaje cinematográfico consistentes.", presenter: "Helena · Presentadora oficial", presenterNote: "El mismo rostro, cabello castaño oscuro, vestuario ejecutivo, ambiente premium y tono consultivo en todas las escenas.",
      scenes: [
        { id: "abertura", number: "01", title: "Apertura", duration: "00:08", line: "Imagine transformar datos, contratos, aprobaciones y evidencias en una jornada inteligente y totalmente trazable.", screen: "ERP → Contrato → Aprobación → Firma → Gobernanza", movement: "Dolly lento de izquierda a derecha.", status: "En producción" },
        { id: "caos", number: "02", title: "El caos invisible", duration: "00:08", line: "En muchas empresas, los datos están en los sistemas, pero los contratos siguen dispersos entre correos, hojas y documentos.", screen: "Datos organizados. Contratos dispersos.", movement: "Acercamiento cinematográfico y líneas rotas.", status: "En producción" },
        { id: "custo", number: "03", title: "El costo oculto", duration: "00:08", line: "Versiones paralelas, aprobaciones perdidas, plazos olvidados y riesgos difíciles de rastrear.", screen: "Retrabajo · Pérdida de visibilidad · Riesgo operacional", movement: "Órbita suave con alertas.", status: "En producción" },
        { id: "nasce", number: "04", title: "Nace DRATOS", duration: "00:08", line: "DRATOS nació para transformar esta complejidad en una jornada estructurada.", screen: "Gobernanza Contractual Inteligente", movement: "Travelling hacia el hub conectado.", status: "En producción" },
        { id: "hub", number: "05", title: "El hub central", duration: "00:08", line: "DRATOS conecta los datos que su empresa ya posee y los transforma en una jornada contractual integrada.", screen: "Conecte · Gobierne · Evolucione", movement: "Apertura amplia del ecosistema.", status: "En producción" },
        { id: "requisicao", number: "06", title: "Solicitud contractual", duration: "00:08", line: "Todo comienza con una solicitud estructurada que reúne información, documentos y responsables.", screen: "Datos completos · Proceso organizado · Menos retrabajo", movement: "Los campos reciben validaciones progresivas.", status: "En producción" },
        { id: "autoria", number: "07", title: "Autoría contractual", duration: "00:08", line: "Los datos aprobados generan una minuta basada en matrices, cláusulas estandarizadas y reglas jurídicas.", screen: "Estandarización · Velocidad · Gobernanza", movement: "La solicitud se transforma en contrato.", status: "En producción" },
        { id: "biblioteca", number: "08", title: "Biblioteca y playbooks", duration: "00:08", line: "El área jurídica mantiene el control mediante cláusulas aprobadas, playbooks y versiones gobernadas.", screen: "Biblioteca Jurídica", movement: "Las cláusulas se incorporan a la minuta.", status: "En producción" },
        { id: "sala", number: "09", title: "Sala Jurídica", duration: "00:08", line: "Todas las interacciones permanecen centralizadas en un ambiente colaborativo y trazable.", screen: "Negociación · Colaboración · Trazabilidad", movement: "Travelling entre comentarios y versiones.", status: "En producción" },
        { id: "diligence", number: "10", title: "Due Diligence", duration: "00:08", line: "La información relevante de la contraparte y las evidencias apoyan decisiones más seguras y documentadas.", screen: "Evidencias · Contexto · Gobernanza", movement: "Acercamiento al panel de validación.", status: "En producción" },
        { id: "assinatura", number: "11", title: "Aprobaciones y firma", duration: "00:08", line: "La versión correcta sigue a firma después de las aprobaciones, con total trazabilidad.", screen: "APROBADO → CONCLUIDO", movement: "Acercamiento sin cortes bruscos.", status: "En producción" },
        { id: "contrato-vivo", number: "12", title: "El contrato se vuelve gestión", duration: "00:08", line: "La firma inicia la gestión continua de obligaciones, plazos y compromisos.", screen: "Contrato Vivo", movement: "Calendario, alertas y obligaciones orbitan el contrato.", status: "En producción" },
        { id: "performance", number: "13", title: "Desempeño contractual", duration: "00:08", line: "Cada contrato tiene su propio modelo de evaluación para acompañar entregas, niveles de servicio y resultados.", screen: "4,8 estrellas · 94% SLA · 98% entregas", movement: "Foco cinematográfico en los indicadores.", status: "En producción" },
        { id: "dossie", number: "14", title: "Expediente auditable", duration: "00:08", line: "Cada decisión, documento, aprobación y evidencia permanece en un único historial auditable.", screen: "Historial · Evidencias · Trazabilidad", movement: "Los elementos convergen al expediente.", status: "En producción" },
        { id: "dashboard", number: "15", title: "Dashboard ejecutivo", duration: "00:08", line: "La información conectada ofrece una visión ejecutiva de la operación contractual en tiempo real.", screen: "Gobernanza · Transparencia · Eficiencia · Desempeño", movement: "Movimiento lateral por los indicadores.", status: "En producción" },
        { id: "encerramento", number: "16", title: "Cierre", duration: "00:08", line: "DRATOS transforma contratos en gobernanza, desempeño, transparencia y decisiones más seguras.", screen: "De la solicitud al desempeño contractual", movement: "Travelling lento por el ecosistema conectado.", status: "En producción" }
      ]
    },
    sources: { eyebrow: "Fuentes de datos y conectores", title: "Comience con los datos que su organización ya posee.", text: "Las integraciones progresivas reducen la redigitación y la dependencia de hojas paralelas sin sustituir sistemas corporativos.", flow: ["Fuentes de datos", "Normalización", "Solicitud", "Jornada contractual"], items: ["ERP", "TOTVS RM", "Sistema de compras", "Hojas de cálculo", "CSV", "APIs", "Formularios", "Registro manual", "Bases externas"], users: ["TI", "Compras", "Jurídico", "Finanzas", "Control de gestión"] },
    platform: {
      eyebrow: "Plataforma completa", title: "Cada etapa conserva el contexto de la anterior.", text: "Explore los módulos de la jornada. Los recursos que dependen de proveedores o integraciones muestran un estado configurable.",
      modules: [
        { id: "solicitacoes", number: "01", title: "Solicitudes de contrato", tagline: "El contrato comienza con una demanda completa, no con un archivo vacío.", summary: "Filtros, búsqueda, paginación y estados organizan solicitudes de Compras o de la Plataforma.", features: ["Proveedor, centro de costo y período", "Datos bancarios y financieros", "Representantes y testigos", "Adjuntos PDF/DOCX", "Homologación y rechazo con motivo", "Archivo con motivo", "Ítems dinámicos y autocompletado", "Identificación fiscal, vigencia, objeto y pago"], status: "Disponible según configuración" },
        { id: "kanban", number: "02", title: "Kanban de contratos", tagline: "Toda la jornada visible en un solo tablero.", summary: "Las tarjetas conectan Autoría, Sala Jurídica, Firma y Concluido.", features: ["Proveedor, número, valor y fecha", "Columnas retráctiles", "Acceso directo a la etapa", "Actualización en tiempo real según integración"], status: "Configurable" },
        { id: "autoria", number: "03", title: "Autoría contractual", tagline: "Transforme una solicitud aprobada en una minuta gobernada sin comenzar de cero.", summary: "Solicitud → Matriz → Parametrización → Minuta.", features: ["Minuta interna o del proveedor", "Editor y versiones", "Campos parametrizados", "Adjuntos y PDF final", "Bypass jurídico configurable", "Rechazo con motivo", "Documento original preservado"], status: "Configurable" },
        { id: "biblioteca", number: "04", title: "Matrices, cláusulas y playbooks", tagline: "El Jurídico mantiene el estándar sin frenar la operación.", summary: "Bibliotecas reutilizables con textos aprobados y parámetros controlados.", features: ["Arrastrar y soltar", "Borrador, revisión y aprobado", "Versiones descontinuadas", "Historial y auditoría", "Playbooks de privacidad y SLA", "Confidencialidad y anticorrupción", "Due Diligence y proveedor crítico"], status: "Configurable" },
        { id: "sala-juridica", number: "05", title: "Sala Jurídica", tagline: "Negociación, revisión y decisión en un ambiente colaborativo y auditable.", summary: "Documento, mensajes y decisiones permanecen en el mismo contexto.", features: ["Visor y mensajes", "Comentarios por cláusula", "Historial y versiones", "Aprobación o retorno a autoría", "Observaciones y pendientes", "Trazabilidad"], status: "Disponible según configuración" },
        { id: "due-diligence", number: "06", title: "Due Diligence", tagline: "Información estructurada para apoyar decisiones más seguras y documentadas.", summary: "Los análisis Tipo 1, Tipo 2 y monitoreo reúnen contexto sin sustituir la decisión humana.", features: ["Datos registrales y estructura societaria", "Certificados e información pública", "Evidencias e informes", "Pendientes y mitigación", "Historial y monitoreo"], status: "Disponible según integración" },
        { id: "ressalvas", number: "07", title: "Salvedades contractuales", tagline: "Puntos de atención formales vinculados al contrato.", summary: "Registro controlado de salvedades activas e históricas.", features: ["Título y descripción", "Clasificación y prioridad", "Adjunto", "Activa o inactiva", "Historial", "Borrado lógico"], status: "Configurable" },
        { id: "assinatura", number: "08", title: "Aprobaciones y firma", tagline: "La versión correcta llega a las personas adecuadas en el orden definido.", summary: "El workflow conecta aprobadores, firmantes y documento final.", features: ["Jurídico, Finanzas y Gestor", "Orden de aprobación", "Representantes y testigos", "Suspensión y retorno a Sala Jurídica", "Reenvío y sincronización", "Webhooks y consulta de contingencia", "Documento firmado", "Firma independiente de PDF"], status: "Disponible según integración" },
        { id: "concluido", number: "09", title: "Contrato concluido", tagline: "El documento final es solo una parte del historial completo.", summary: "Un stepper conserva solicitudes, firmantes, cuotas, visualizaciones e historial final.", features: ["Solicitudes vinculadas", "Firmantes", "Cuotas financieras", "Documento firmado", "Auditoría de visualización", "Historial final"], status: "Disponible según configuración" },
        { id: "obrigacoes", number: "10", title: "Obligaciones y monitoreo", tagline: "La firma no termina la jornada. Inicia la ejecución gobernada.", summary: "Plazos, responsables y evidencias convierten el contrato en una rutina gestionable.", features: ["Calendario y alertas", "Reajustes y vencimientos", "Entregas y SLA", "Renovaciones y compromisos", "Evidencias", "Monitoreo de la contraparte"], status: "En evolución" },
        { id: "performance-modulo", number: "11", title: "Desempeño contractual", tagline: "Cada contrato puede evaluarse por lo que realmente importa.", summary: "Criterios, pesos, escalas y ciclos configurables por contrato.", features: ["Modelos propios o existentes", "Justificaciones y evidencias", "Comparación de ciclos", "Consolidación por proveedor", "Estrellas, nota, porcentaje y SLA", "Checklist y criterios ponderados"], status: "En evolución" },
        { id: "dossie", number: "12", title: "Expediente auditable", tagline: "De la solicitud al desempeño, cada decisión permanece en un historial verificable.", summary: "Solicitudes, versiones, aprobaciones, documentos, evidencias y logs convergen en una línea de tiempo.", features: ["Matriz y cláusulas", "Sala Jurídica y Due Diligence", "Salvedades y aprobaciones", "Firma y obligaciones", "Desempeño y evidencias", "Trazabilidad append-only"], status: "Configurable" },
        { id: "juridico", number: "13", title: "Central y Consulta Jurídica", tagline: "El Jurídico centraliza contratos y demandas consultivas sin perder contexto.", summary: "Consultas y contratos comparten urgencia, historial y acceso por perfil.", features: ["Asunto, descripción y urgencia", "Adjunto y chat", "Historial y finalización", "Demandas consolidadas", "Volumen y acceso rápido"], status: "Disponible según configuración" },
        { id: "notificacoes", number: "14", title: "Notificaciones", tagline: "Cada persona recibe lo relevante para su contexto.", summary: "El correo y las notificaciones in-app mantienen a las personas informadas y vinculadas al evento.", features: ["SMTP y plantillas", "Perfiles y contexto", "Logs y pruebas", "Campana e indicador", "Leída o no leída", "Enlace directo y eventos automáticos"], status: "Configurable" },
        { id: "configuracoes", number: "15", title: "Central de configuraciones", tagline: "Reglas operativas administradas en un solo lugar.", summary: "Matrices, usuarios, notificaciones, tareas e integraciones pueden ser gobernadas por perfiles autorizados.", features: ["Matrices de contrato", "Usuarios y perfiles", "SMTP y notificaciones", "Tareas programadas", "Integración TOTVS RM", "Datos de prueba en ambientes controlados"], status: "Disponible según perfil" }
      ]
    },
    performance: {
      eyebrow: "Desempeño contractual", title: "Cada contrato puede evaluarse por lo que realmente importa.", text: "Seleccione un modelo y defina criterios, pesos, escala, periodicidad y responsables. Exija justificaciones, adjunte evidencias y acompañe la evolución por ciclo y proveedor.", disclaimer: "Valores meramente demostrativos.", flow: ["Obligaciones", "Evidencias", "Desempeño", "Decisión"], publicValue: "Fiscalización objetiva, transparencia, seguimiento de proveedores y rendición de cuentas para operaciones públicas y reguladas.", videoScene: 12, score: { label: "Evaluación general", value: "4,8", scale: "de 5", stars: "★★★★★" },
      indicators: [{ label: "SLA cumplido", value: "94%", progress: 94 }, { label: "Entregas realizadas", value: "98%", progress: 98 }, { label: "Incidencias", value: "2", progress: 18 }], models: ["1 a 5 estrellas", "Nota de 0 a 10", "Porcentaje", "SLA cumplido, parcial o incumplido", "Excelente a crítico", "Checklist", "Criterios ponderados", "Evaluación cualitativa", "Indicadores propios"], examples: [{ title: "Seguridad", items: ["Cobertura de puestos", "Tiempo de respuesta", "Incidencias", "Calidad del equipo", "SLA"] }, { title: "Limpieza", items: ["Calidad", "Frecuencia", "Reclamos", "Conformidad", "Auditorías"] }, { title: "Tecnología", items: ["Disponibilidad", "Incidentes", "Tiempo de resolución", "Experiencia", "SLA"] }, { title: "Gobierno y regulados", items: ["Metas", "Entregas", "Indicadores", "Fiscalización", "Evidencias"] }]
    },
    dossierSpotlight: { eyebrow: "Expediente Auditable", title: "El desempeño también se convierte en evidencia.", text: "Solicitud, matriz, versiones, decisiones, Due Diligence, salvedades, firma, obligaciones y ciclos de evaluación convergen en un historial verificable.", items: ["Decisiones y aprobaciones", "Documentos y versiones", "Obligaciones y plazos", "Desempeño y evidencias", "Logs append-only"], proof: "De la solicitud a la ejecución: contexto preservado para auditoría, fiscalización y rendición de cuentas.", videoScene: 13 },
    dashboard: { eyebrow: "Visión ejecutiva", title: "De la operación al indicador sin perder el detalle.", text: "Seis perspectivas conectan contratos, proveedores, costos, vencimientos y datos para apoyar decisiones.", views: ["Menú Ejecutivo", "Proveedores", "Centro de Costo", "Categoría y Naturaleza", "Vencimientos", "Base de Datos"], filters: ["Compañía", "Sucursal", "Múltiples sucursales", "Centro de costo", "Período", "Drilldown", "Exportación"], kpis: [{ label: "Contratos activos", value: "1.248", delta: "+8,4%" }, { label: "Valor total", value: "US$ 16,2 mi", delta: "+3,1%" }, { label: "En negociación", value: "86", delta: "12 críticos" }, { label: "Desempeño promedio", value: "4,6", delta: "de 5" }, { label: "Obligaciones abiertas", value: "142", delta: "18 próximas" }, { label: "SLA crítico", value: "7", delta: "requiere atención" }], disclaimer: "Datos ficticios para demostración visual.", videoScene: 14 },
    integrations: {
      eyebrow: "Ecosistema conectado", title: "Integre progresivamente sin limitar la plataforma a un proveedor.", text: "TOTVS RM es una integración inicial prioritaria y una prueba concreta de conectividad, no una limitación de DRATOS.",
      items: [{ name: "TOTVS RM", type: "ERP prioritario", status: "Disponible según proyecto" }, { name: "TOTVS Firma Electrónica", type: "Firmador inicial", status: "Disponible según integración" }, { name: "Sistema de Compras", type: "Origen de demandas", status: "Configurable" }, { name: "APIs REST", type: "Integración", status: "Configurable" }, { name: "Webhooks", type: "Eventos", status: "Configurable" }, { name: "SMTP", type: "Comunicación", status: "Configurable" }, { name: "Hojas y CSV", type: "Importación", status: "Configurable" }, { name: "Otros ERPs y firmadores", type: "Ecosistema", status: "Planificado según proyecto" }],
      totvs: { title: "Integración inicial con TOTVS RM", text: "Las consultas y sincronizaciones pueden conectar proveedores, productos y servicios, compañías, sucursales, centros de costo, usuarios, contratos y estados.", features: ["Transporte de contratos", "Sincronización de estados", "Webhooks cuando estén disponibles", "Consulta de contingencia", "Trazabilidad de la integración"] }
    },
    videoLibrary: { eyebrow: "Demostraciones por funcionalidad", title: "Vea la jornada en acción, etapa por etapa.", text: "Videos breves presentados por Helena muestran la plataforma desde la visión general hasta el dashboard ejecutivo.", sceneIndexes: [0, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14] },
    access: { eyebrow: "Perfiles y control de acceso", title: "La persona correcta, en el contexto correcto, con el permiso correcto.", text: "RBAC y segregación contextual controlan el acceso en frontend y backend sin exponer detalles sensibles.", profiles: ["ADMIN", "ESPECIALISTA", "JURÍDICO", "GESTOR", "FIRMANTE", "INDICADORES", "AUDITORÍA", "COMPRAS"], contexts: ["Compañía", "Sucursal", "Centro de costo", "Múltiples centros", "Acceso interno y externo"] },
    security: { eyebrow: "Seguridad y arquitectura", title: "Controles enterprise en toda la jornada.", text: "La arquitectura combina autenticación, segregación, auditoría y resiliencia. El diseño final depende del ambiente y las integraciones de cada organización.", items: ["JWT", "RBAC", "Segregación por contexto", "Trazabilidad append-only", "Logs y auditoría", "Idempotencia y hash", "Webhooks y reintentos", "Consulta de contingencia", "Timeouts y caché", "Rutas protegidas", "Almacenamiento documental", "Multiempresa y multisucursal"], stackTitle: "Stack técnico", stackText: "Área técnica secundaria", stackNote: "Stack de la plataforma DRATOS. Esta landing usa HTML, CSS y JavaScript puros para publicación estática." },
    publicSector: { eyebrow: "Sector público y organizaciones reguladas", title: "Gobernanza, transparencia y desempeño para operaciones que exigen rendición de cuentas.", text: "Estructure contratos de servicios continuos, metas, fiscalización, SLA, evidencias y desempeño en múltiples unidades y centros de costo.", items: ["Proveedores y servicios continuos", "Metas y entregas", "Fiscalización y SLA", "Evidencias y auditoría", "Múltiples unidades", "Historial y rendición de cuentas"] },
    plans: { eyebrow: "Planes", title: "Una configuración para cada etapa de madurez.", text: "Los volúmenes, módulos, integraciones y servicios se definen después del diagnóstico.", items: [{ name: "Sandbox", price: "Prueba orientada", description: "Conozca la jornada con un escenario demostrativo.", features: ["Ambiente guiado", "Datos demostrativos", "Sesión de diagnóstico"] }, { name: "Essential", price: "A partir de", description: "Organice solicitudes, autoría y documentos.", features: ["Solicitudes", "Matrices básicas", "Hojas y CSV"] }, { name: "Professional", price: "Consultar", description: "Amplíe la gobernanza jurídica y posfirma.", features: ["Sala Jurídica", "Playbooks", "Obligaciones", "Due Diligence"] }, { name: "Business Integrado", price: "Consultar", description: "Conecte la jornada a sistemas corporativos.", features: ["Conector asistido", "APIs y monitoreo", "Expediente avanzado"], featured: true }, { name: "Enterprise", price: "Proyecto personalizado", description: "Arquitectura para operaciones complejas.", features: ["Multiempresa", "Perfiles avanzados", "Integraciones y SLA"] }] },
    founding: { eyebrow: "Programa de lanzamiento", title: "DRATOS Founding Clients", text: "Construya un caso aplicado con diagnóstico, implantación orientada y acompañamiento de los primeros resultados.", items: ["Diagnóstico del flujo contractual", "Matriz y playbook inicial", "Integración e importación de datos", "Capacitación", "Acompañamiento", "Construcción del caso", "Evaluación de resultados"] },
    faq: { eyebrow: "Preguntas frecuentes", title: "Comience con claridad.", items: [["¿DRATOS sustituye al ERP?", "No. DRATOS conecta y gobierna la jornada contractual usando datos que la organización ya posee."], ["¿Necesito tener TOTVS?", "No. TOTVS RM es una integración inicial prioritaria, pero se aceptan otras fuentes."], ["¿Es posible comenzar con hojas de cálculo?", "Sí. Las hojas y CSV permiten una implantación progresiva."], ["¿Cómo entran los datos?", "Por formularios, registro manual, importaciones, APIs o conectores configurados."], ["¿El Jurídico controla matrices y cláusulas?", "Sí. Matrices, versiones, estados y playbooks mantienen la gobernanza jurídica."], ["¿Cómo funciona la Sala Jurídica?", "Centraliza documentos, comentarios, versiones, pendientes y decisiones."], ["¿La plataforma posee firma electrónica?", "La jornada integra firma electrónica según el firmador y el proyecto."], ["¿Cómo funciona Due Diligence?", "Reúne datos, evidencias y pendientes para apoyar el análisis humano documentado."], ["¿Qué es Desempeño Contractual?", "Es la evaluación periódica de entregas, niveles de servicio, criterios y resultados."], ["¿Cada contrato puede tener indicadores propios?", "Sí. Modelos, criterios, pesos, escalas y periodicidades son configurables."], ["¿Qué es el Expediente Auditable?", "Es el historial verificable de documentos, versiones, decisiones, aprobaciones, evidencias y eventos."], ["¿Cómo funcionan los permisos?", "Perfiles y contextos como compañía, sucursal y centro de costo delimitan el acceso."], ["¿DRATOS atiende al gobierno?", "Puede apoyar operaciones públicas y reguladas que requieren evidencias y rendición de cuentas."], ["¿Se pueden integrar otros ERPs?", "Sí. El diseño contempla APIs, webhooks, importaciones y conectores por proyecto."], ["¿Cómo funciona el piloto?", "Comienza con diagnóstico, escenario prioritario, configuración orientada y criterios de evaluación acordados."]] },
    finalCta: { eyebrow: "Demostración aplicada", title: "¿Presentamos DRATOS aplicada a la realidad de su organización?", text: "Mostramos la jornada completa usando sus contratos, fuentes de datos, áreas, criterios de aprobación, obligaciones e indicadores de desempeño.", signature: "De la solicitud al desempeño contractual." },
    form: {
      title: "Agende una demostración aplicada", text: "Cuéntenos sobre su operación. Sin un endpoint configurado, la confirmación abrirá su cliente de correo con destino a contato@dratos.com.br.", fields: {
        name: { label: "Nombre", placeholder: "Su nombre", required: true }, company: { label: "Empresa", placeholder: "Nombre de la organización", required: true }, role: { label: "Cargo", placeholder: "Su función", required: true }, email: { label: "Correo corporativo", placeholder: "nombre@empresa.com", required: true }, phone: { label: "Teléfono (opcional)", placeholder: "+00 000 000 000", required: false }, erp: { label: "ERP actual", placeholder: "Seleccione", required: true, options: ["TOTVS RM", "SAP", "Oracle", "Otro ERP", "Hojas / sin ERP"] }, volume: { label: "Volumen aproximado de contratos", placeholder: "Seleccione", required: true, options: ["Hasta 100", "101 a 500", "501 a 2.000", "2.001 a 10.000", "Más de 10.000"] }, challenge: { label: "Principal desafío", placeholder: "Describa brevemente el escenario", required: true }, interest: { label: "Interés", placeholder: "Seleccione", required: true, options: ["Demostración", "Diagnóstico", "Programa Founding Clients", "Integración", "Alianza"] }, privacy: { label: "Acepto el uso de estos datos para responder a esta solicitud.", required: true }
      }, demoSuccess: "Su cliente de correo se abrió con la solicitud dirigida a contato@dratos.com.br. Revise el mensaje antes de enviarlo.", sendSuccess: "Solicitud enviada con éxito.", error: "No fue posible enviar ahora. Revise los datos o inténtelo de nuevo.", validation: "Complete los campos obligatorios y acepte la declaración de privacidad."
    },
    footer: { descriptor: "Gobernanza Contractual Inteligente", text: "Datos, decisiones y desempeño en una jornada verificable.", contactLabel: "Contacto", links: [["Jornada", "#jornada"], ["Plataforma", "#plataforma"], ["Seguridad", "#seguranca"], ["FAQ", "#faq"]], copyright: "© 2026 DRATOS. Todos los derechos reservados.", privacy: "Privacidad", privacyNote: "En esta demostración, sin un endpoint configurado, el formulario solo prepara un mensaje en el cliente de correo del visitante. El envío ocurre únicamente después de su confirmación." },
    videoModal: { production: "Video en producción", productionText: "Este espacio está preparado para recibir el video, poster, subtítulos y transcripción de la escena.", transcript: "Transcripción", sceneDirection: "Dirección de escena" },
    toast: { theme: "Tema actualizado.", language: "Idioma actualizado.", copied: "Contenido copiado.", plan: "Plan seleccionado para la conversación." }
  });

  window.DRATOS_CONTENT.es.journey.scenes.forEach((scene, index) => {
    scene.video = base.journey.scenes[index].video;
    scene.captions = base.journey.scenes[index].captions;
    scene.poster = base.journey.scenes[index].poster;
    scene.duration = "00:10";
    scene.status = "Disponible";
  });

  window.DRATOS_CONTENT.es.platform.modules.forEach((module) => {
    const source = base.platform.modules.find((item) => item.id === module.id);
    module.videoScene = source?.videoScene ?? null;
  });
})();
